import { program_1_A0, program_1_A, program_1_B0, program_1_B } from "./01/program.js";
import { program_2_A0, program_2_A, program_2_B0, program_2_B } from "./02/program.js";
import { program_3_A0, program_3_A, program_3_B0, program_3_B } from "./03/program.js";
import { program_4_A0, program_4_A, program_4_B0, program_4_B } from "./04/program.js";
import { program_5_A0, program_5_A, program_5_B0, program_5_B } from "./05/program.js";
import { program_6_A0, program_6_A, program_6_B0, program_6_B } from "./06/program.js";
import { program_7_A0, program_7_A, program_7_B0, program_7_B } from "./07/program.js";
import { program_8_A0, program_8_A, program_8_B0, program_8_B } from "./08/program.js";
console.log("##### Day 01 #####");
console.log("\tProblem A: ", await program_1_A());
console.log("\tProblem B: ", await program_1_B());
console.log("##### Day 02 #####");
console.log("\tProblem A: ", await program_2_A());
console.log("\tProblem B: ", await program_2_B());
console.log("##### Day 03 #####");
console.log("\tProblem A: ", await program_3_A());
console.log("\tProblem B: ", await program_3_B());
console.log("##### Day 04 #####");
console.log("\tProblem A: ", await program_4_A());
console.log("\tProblem B: ", await program_4_B());
console.log("##### Day 05 #####");
console.log("\tProblem A: ", await program_5_A());
console.log("\tProblem B: es un 'brute force' que tarda horas y que tengo que rehacer");
//console.log("\tProblem B: ", await program_5_B());
console.log("##### Day 06 #####");
console.log("\tProblem A: ", await program_6_A());
console.log("\tProblem B: ", await program_6_B());
console.log("##### Day 07 #####");
console.log("\tProblem A: ", await program_7_A());
console.log("\tProblem B: ", await program_7_B());
console.log("##### Day 08 #####");
//console.log("\tProblem A: ", await program_8_A());
console.log("\tProblem B: ", await program_8_B());
